slack:
    channel: channel-test
    emoji: emoji-test
    fileName: names.txt
    iconUrl: icon-url-test
    name: xpbot-test
    token: token-test
    messageUrl: message-url-test
    rtmUrl: rtm-url-test
