slack:
    name: ${SLACK_NAME}
    token: ${SLACK_TOKEN}
    iconUrl: ${SLACK_ICON_URL}
    rtmUrl: https://slack.com/api/rtm.connect?token=
    messageUrl: https://slack.com/api/chat.postMessage?
    generalChannel: ${SLACK_GENERAL_CHANNEL}